
server:
  port: 8100

spring:
  application:
    name: intern-product-service
  jpa:
    hibernate:
      ddl-auto: update
    hikari:
      minimum-idle: 50
      maximum-pool-size: 50
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:

    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:test
    #    username: sa

    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://rds-aurora-postgresql-instance-0.cgvuywkbcpuj.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: test1357!
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  jpa:
#    hibernate:
#      ddl-auto: update
##      ddl-auto: create-drop
##    show-sql: true
##    generate-ddl: true
##    defer-datasource-initialization: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username: sa

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/te/st
#    driver-class-name: org.h2.Driver



logging:
  level:
    com.lgu.productservice: DEBUG